version: "3.8"

services:

  backend:
    image: travelblog-backend
    container_name: tb-backend
    ports:
      - "8083:5001" 
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always

  frontend:
    image: travelblog-frontend
    container_name: tb-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
